global:
#  registry:
#    url: evnfm-reg.mhna2rhck01erevnfm06.mcc404.mnc090.airtel.com
#    pullSecret: evnfmregcred
#  pullSecret: evnfmregcred 
  ericsson:
    licensing:
      licenseDomains:
        - productType:
          customerId:
          swltId:
  licensing:
    sites:
      - hostname:
        ip:
        priority: 30
      - hostname: 
        ip:
        priority: 50
  timezone: Asia/Kolkata
