
global:
#  registry:
#    url: evnfm-reg.mhna2rhck01erevnfm06.mcc404.mnc090.airtel.com
#    pullSecret: evnfmregcred
#  pullSecret: evnfmregcred 
  ericsson:
    licensing:
      licenseDomains:
        - productType:
          customerId: 
          swltId:
  licensing:
    sites:
      - hostname:
        ip:
        priority: 30
      - hostname:
        ip:
        priority: 50
  timezone: Asia/Kolkata
  nodeSelector:
    eric-pod: "paco"
  pcfw:
    enabled: false

eric-tm-partition-distributor:
  enabled: true
  replicaCount: 5                         ###No of replica=2 by Candy Dimentioning but in CPI recommended is replica=3
  resources:
    partitionDistributor:
      limits:
        cpu: 1                            ###CPU limit is same for 1.23 and 1.18.
        memory: 512Mi                     ###CPU limit is same for 1.23 and 1.18.
      requests:
        cpu: 0.2                          ###CPU request as per 1.23 Candy Dimentioning.
        memory: 0.1Gi                     ###Memory request as per 1.23 Candy Dimentioning.

eric-pc-up-data-plane:
  enabled: true
  allowNetworkConfigChanges: false
  deployment:
    pinThreads: true
  acceleratedIo:
    driver: bifurcated
    enabled: true
    pciDeviceArguments:
      - 'rxq_cqe_comp_en=0'
  replicaCount: 72
  resources:
#    dataPlaneAt:
#      requests:
#        cpu: 3
#        memory: 16Gi
#        hugepages-1Gi: 2Gi
#        ephemeral-storage: 16Gi
#      limits:
#        cpu: 3
#        memory: 16Gi
#        hugepages-1Gi: 2Gi
#        ephemeral-storage: 16Gi
    dataPlane:
      requests:
        openshift.io/sriovleftmellanox: 1
        openshift.io/sriovrightmellanox: 1
        hugepages-1Gi: 2Gi
        cpu: 16
        memory: 12Gi                                   ## NIR mentions increase in memory from 1.23
      limits:
        openshift.io/sriovleftmellanox: 1
        openshift.io/sriovrightmellanox: 1
        hugepages-1Gi: 2Gi
        cpu: 16
        memory: 12Gi
#  at:
#    vhostuserPorts:
#      queues: 2
#      queueSize: 8192
#    log:
#      backupLogsPeriod: "1"              ###Added to have 1 day log instead of 5days as per CPI.
#      showtechInterval: "30"             ###showtech log collection interval is 15 minutes,  Ericsson recommends setting the value to 30.
  sidecar:
    at: false
  podDisruptionBudget:
    maxUnavailable: 6
  interfaces:
    - name: net1
      type: host-device
#      resourceName: 'openshift.io/sriovleftmellanox'
      networkAttachmentDefinition: false
    - name: net2
      type: host-device
#      resourceName: 'openshift.io/sriovrightmellanox'
      networkAttachmentDefinition: false
  tolerations:
    - key: dedicated
      operator: Equal
      value: "HT-PCG-DP"
      effect: "NoSchedule"
  reporting:
    ebm:
      enabled: false
  ping:
    enabled: true
  updateStrategy:               ###Rolling update
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

eric-pc-up-pfcp-endpoint:
  enabled: true
  replicaCount: 90                   ###No of replica=48 by Candy Dimentioning but in PCG 1.18 replica=58
  resources:
    pfcpEndpoint:
      limits:
        cpu: 1                       ###CPU limit is 1 CPU for 1.23 and 0.8 CPU is for 1.18.
        memory: 4Gi                  ###Memory limit is 4Gi for 1.23 and 1Gi is for 1.18.
      requests:
        cpu: 0.8                     ###CPU request as per 1.23 Candy Dimentioning.
        memory: 1Gi                  ###Memory request as per 1.23 Candy Dimentioning.
  podDisruptionBudget:
    maxUnavailable: 24                                                                                      

eric-pc-kvdb-rd-server:
  enabled: true
  numberOfMaster: 50             ###No of replica=50 for 500gbps
  resources:
    node:
      limits:
        cpu: 2                  ###CPU limit is 1-2 CPU for 1.23 and 1.05 CPU is for 1.18. Need to consider 1.5 CPU as per PDU.
        memory: 12Gi               ###Memory limit is 3-12Gi for 1.23 and 5Gi is for 1.18.
      requests:
        cpu: 1                     ###CPU request as per 1.23 Candy Dimentioning.
        memory: 4Gi                ###Memory request as per 1.23 Candy Dimentioning.

eric-probe-event-report-broker:
  enabled: false

eric-pc-firewall-coordinator-at:
  enabled: false
  at:
    log:
      backupLogsPeriod: "1"                ###Added to have 1 day log instead of 5days as per CPI.
      showtechInterval: "30"               ###showtech log collection interval is 15 minutes,  Ericsson recommends setting the value to 30.
  replicaCount: 2
  resources:
    at:
      limits:
        cpu: 2                    ###CPU limit is 2 CPU for 1.23 and 2 CPU is for 1.18.
        memory: 8Gi               ###Memory limit is 7Gi for 1.23 and 8Gi is for 1.18.
      requests:
        cpu: 1                     ###CPU request as per 1.23 Candy Dimentioning.
        memory: 8Gi                ###Memory request as per 1.23 Candy Dimentioning.

eric-pc-routing-aggregator:
  enabled: true
  resources:
    routingAggregator:
      limits:
        cpu: 2                       ###CPU limit is 2 CPU for 1.23 and 2 CPU is for 1.18.
        memory: 4Gi                  ###Memory limit is 4Gi for 1.23 and 4Gi is for 1.18.
      requests:
        cpu: 0.5                     ###CPU request as per 1.23 Candy Dimentioning.
        memory: 1Gi                  ###Memory request as per 1.23 Candy Dimentioning.
  podDisruptionBudget:
    maxUnavailable: 2
  updateStrategy:                    ###Rolling update
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 25%

  replicaCount: 8                    ###CPI recommends deploying 8 Routing Aggregator replicas to support 10,000,000 UE session. Candy replica=2.

eric-pc-routing-engine:
  enabled: true
  resources:
    eric-pc-routing-engine:
      limits:
        cpu: 1                      ###CPU limit is 1-4 CPU for 1.23 and 1 CPU is for 1.18.
        memory: 1Gi                 ###Memory limit is 500Mi-3Gi for 1.23 and 500Mi is for 1.18.
      requests:
        cpu: 0.1                    ###CPU request as per 1.23 Candy Dimentioning.
        memory: 500Mi               ###Memory limit is 4Gi for 1.23 and 4Gi is for 1.18.
  interfaces:
    type: predefine
    predefineNetworks:
      - name: eric-pc-routing-engine

#cnom-loadBalancer-service:
#  enabled: true
#  loadBalancerIP: 2401:4900:54:e00::1630
#  annotations:
#    metallb.universe.tf/address-pool: "pcg-oam"
#    metallb.universe.tf/allow-shared-ip: "pcg-oam"
snmp-alarm-provider-secret-creation:
  enabled: false

eric-odca-isp-event-monitor:
  enabled: true
  resources:
  pciem:
    limits:
      memory: 512Mi                                         ##updated memoery as per optimization in NESA PCG.
    requests:
      memory: 128Mi                                         ##updated memoery as per optimization in NESA PCG.

eric-pc-pm-init:
  enabled: true
  resources:
    pmInit:
      limits:
        cpu: "100m"                                         ##updated memoery as per optimization in NESA PCG.
      requests:
        cpu: "50m"                                          ##updated memoery as per optimization in NESA PCG.
        memory: # 256Mi
        
eric-pm-resource-monitor:
  resources:
    pmrm:
      limits:
        memory: 512Mi
      requests:
        memory: 128Mi
        
        
eric-cloud-native-base:
  enabled: true

  eric-data-object-storage-mn:                              ###Object-storage pvc updated to 500Gi from default.
    persistentVolumeClaim:
      size: 500Gi
    resources:
      kes:
        requests:
          memory: 200Mi                                     ###kes container memory optimized as per live reference.
        limits:
          memory: 400Mi                                     ###kes container memory optimized as per live reference.

  eric-cm-mediator:
    enabled: true
    replicaCount: 2

  eric-data-message-bus-kf:
    enabled: true
    nodeSelector:
      eric-pod: paco

  eric-data-search-engine:
    autoSetRequiredWorkerNodeSysctl: false
    enabled: true
    replicaCount:                                          ### Replicas updatedas per JIRA: GBPS-6002 eric-log-transformer pod in 2/3 Ready state
      data: 6
      ingest: 2
      master: 3
    persistence:
      data:
        persistentVolumeClaim:                              ###TBD, default is 10Gi
          size: "72Gi"
    jvmHeap:                                               ###added as per JIRA: GBPS-6002 eric-log-transformer pod in 2/3 Ready state
      data: 3072m
      ingest: 2048m
      master: 512m
    resources:                                             ###Resource updated as per JIRA: GBPS-6002 eric-log-transformer pod in 2/3 Ready state
      data:
        limits:
          cpu: "3300m"
          memory: "10Gi"                                   ###updated memoery as per optimization in NESA PCG.
#        requests:
#          cpu: "500m"
#          memory: "10Gi"
      master:
        limits:
          memory: "2Gi"                                    ###updated memoery as per optimization in NESA PCG.
      ingest:
        limits:
          cpu: "750m"
          memory: "4Gi"

  eric-dst-agent:
    enabled: true
    tolerations:
      - key: dedicated
        operator: Equal
        value: "HT-PCG-DP"
        effect: "NoSchedule"

  eric-fh-snmp-alarm-provider:
    yang:                               ###added for SNMP config via Day1
      enabled: true
      readConfigFromSecret: false
    enabled: true
    service:
      externalIPv6 :
        enabled: true
        loadBalancerIP: 2401:4900:54:e00::1630
        annotations:
          addressPoolName: pcg-oam
          sharedVIPLabel: pcg-oam
        secretName: snmp-alarm-provider-config

  eric-lm-combined-server:
    enabled: true
 #   licenseServerClient:
 #     licenseServer:
 #       thrift:
 #         host: 10.106.150.8        #Uppal NELS
 #         port: 9095
 #   licenseServerIpAddresses:
 #   # licenseServerIpAddresses.ip1
 #   ip1: 10.106.150.8
 #   # licenseServerIpAddresses.ip2
 #   ip2: 10.106.155.128             #Vijaywada NELS

  eric-log-shipper:
    enabled: true
    resources:
      metrics:
        requests:
          memory: 100Mi
        limits:
          memory: 200Mi
    logshipper:
      privileged: true
    tolerations:
      - key: dedicated
        operator: Equal
        value: "HT-PCG-DP"
        effect: "NoSchedule"

  eric-log-transformer:
    enabled: true
    replicaCount: 6                                 ###replicas updated from 4 to 6.
    resources:
      logtransformer:
        limits:
          cpu: 2000m  
          memory: 12Gi                              ###updated to 12Gi
        requests:
          cpu: 500m
          memory: 12Gi
        jvm:                                        ### To be adjusted, should not cross 8 Gi
          initialMemoryAllocationPercentage: # 67
          smallMemoryAllocationMaxPercentage: # 50
          largeMemoryAllocationMaxPercentage: # 67
    egress:
      syslog:
        defaultSeverity: 6
        certificates:
          asymmetricKeyCertificateName: #log-syslog-client
          trustedCertificateListName: #log-syslog-client
        enabled: true
        exclusions:
          - field: "[extra_data][asi][log_plane]"
            value: alarm
        inclusions:
          - field: "[facility]"
            value: log audit
          - field: "[facility]"
            value: local3
          - field: "[facility]"
            value: security/authorization messages
          - contains: -privacy-
            field: "[metadata][category]"
        remoteHosts:
          - host: 2401:4900:0024:0506::d                        #SIEM hashed out after testing
            port: 61542
          - host: 2401:4900:54:e00::1634                        #CAC-Alog from IP Plan
            port: 514            
        tls:
          enabled: false
        filter: ruby { code => "event.set('message', event.get('[message]')+' '+event.get('[subject]').to_s || '-')" }
        


  eric-odca-diagnostic-data-collector:
    enabled: true
    resources:
      diagnostic-data-collector:
        limits:
          memory: 8Gi                          ###Memory limit updated to 6Gi from 8Gi as per 1.23 dimentioning.
          cpu: 5                               ###CPU updated to 5 from 10 as per 1.23 dimentioning.
          ephemeral-storage: 120Gi              ###Ephemeral-Storage updated to 80Gi from 120Gi as per 1.23 dimentioning.
#    env:
#      sftpFileLocation: "BHPATRHCK05ERPCGUP11/DDC"
#      sftphost: 10.49.82.71:2222
#      fileCollectorLocations:
      #- coredump/core
      #- eric-pmbr-rop-file-store
      #- a10net


  eric-pm-server:
    enabled: true
    resources:
      eric-pm-server:
        limits:
          cpu: 60                                ###CPU updated to 60 from 7.5 as per 1.23 dimentioning.
          memory: 65Gi                           ###Memory limit updated to 65Gi from 48Gi as per 1.23 dimentioning Timeseries for NESA is 4.7M
        requests:
          cpu: 6
          memory: 44Gi
      eric-pm-exporter:
        limits:
          memory: 128Mi                   ###Updated in TN PCG to clear alarm.
        requests:
          memory: 32Mi                    ###Updated in TN PCG to clear alarm.
      eric-pm-reverseproxy:
        limits:
          memory: 256Mi                    ###Updated in TN PCG to clear alarm.
        requests:
          memory: 64Mi
    rbac:
      appMonitoring:
        enable: true
        configFileCreate: false
    server:
      retention: 3d
      configMapOverrideName: eric-pc-gateway-pm-server
      persistentVolume:
        enabled: true
        size: 213Gi                       ###persistentVolume updated to 213Gi from 144Gi as per 1.23 dimentioning as Timeseries for NESA. is 4.7M

  eric-si-application-sys-info-handler:
    enabled: true
    resources:
      eric-si-application-sys-info-handler:
        limits:
          memory: 200Mi
        requests:
          memory: 100Mi
    asih:
      applicationId: "BHPATRHCK05ERPCGUP11"

  eric-data-distributed-coordinator-ed:
    enabled: true
    resources:
      metricsexporter:
        limits:
          memory: 128Mi
      dced:
        limits:
          memory: "2Gi"             ##updated memoery as per optimization in NESA PCG.
        requests:
          memory: "800Mi"           ##updated memoery as per optimization in NESA PCG.  
          
  eric-sec-sip-tls:
    resources:
      sip-tls:
        limits:
          memory: 800Mi
      sip-tls-supervisor:
        limits:
          memory: 800Mi

  eric-tm-ingress-controller-cr:
    enabled: true
    resources:
      envoy:
        requests:
          memory: 250Mi
        limits:
          memory: 750Mi
    ingressClass: OAM-IngressPCGUPClass
    rbac:
      create: true
    service:
      externalIPv4:
        enabled: false
#        loadBalancerIP: <Ingress Controller Service IPv4 address>
      externalIPv6:
        enabled: true
        loadBalancerIP: 2401:4900:54:e00::1630
        annotations:
          addressPoolName: pcg-oam
#          metallb.universe.tf/address-pool: pcg-oam
#          metallb.universe.tf/allow-shared-ip: pcg-oam
          sharedVIPLabel: pcg-oam
      externalTrafficPolicy: Cluster
    clientCertificate:
      enabled: true
    envoyWorkloadMode:
      daemonset:
        enabled: false
      deployment:
        enabled: true
        
  eric-sec-key-management:
    resources:
      metrics:
        requests:
          memory: 20Mi
        limits:
          memory: 100Mi
eric-cloud-native-nf-additions:
  enabled: true

  eric-pm-bulk-reporter:
    env: 
      iscompressed: true
      nodeName: "BHPATRHCK05ERPCGUP11"
    applicationId:
      enabled: false
      
      
  eric-cm-yang-provider:
    enabled: true
    service:
      externalIPv6:
        loadBalancerIP: 2401:4900:54:e00::1630
        enabled: true
        annotations:
          addressPoolName: pcg-oam
#          metallb.universe.tf/address-pool: pcg-oam
#          metallb.universe.tf/allow-shared-ip: pcg-oam
          sharedVIPLabel: pcg-oam

  eric-data-sftp-server:
    service:
      allocateLoadBalancerNodePorts: true
      externalIPv6:
        loadBalancerIP: 2401:4900:54:e00::1630
        enabled: true
        annotations:
          addressPoolName: pcg-oam
#          metallb.universe.tf/address-pool: pcg-oam
#          metallb.universe.tf/allow-shared-ip: pcg-oam
          sharedVIPLabel: pcg-oam

  eric-sec-ldap-server:
    enabled: true
    replicaCount: 2
    adminCredentials:
      adminuser: "day0"
      adminpasswd: "$6$Ik8pnS07GvkRktZ8$izS5QyYOmLTJ/bOOTQISMqBHloYjOJYCCnsD.aT9J3sFoNdcM9/84iKpnXtz/zJOWsgv43qwy0vUiIJ.P4Xl40"    ##Encrypoted password is WeakPas$pcgD-1
      ##Change this password after initial login.
  eric-cnom-server:
    enabled: true
    authentication:
      session:
        singleSession: false
    resources:
      server:
        limits:
          memory: 800Mi
        requests:
          memory: 800Mi
    ingress:
      enabled: true
      hostname: bhpatrhck05erpcgup11.cnom.5gc.mnc052.mcc405.3gppnetwork.org   ### PCG CNOM Hostname
      ingressClass: OAM-IngressPCGUPClass
      certificates:
        enabled: true
      tls:
        verifyClientCertificate: optional
    server:
      basePath: login
    service:
      endpoints:
        api:
          tls:
            enforced: optional
            ca:
              - name: eric-tm-ingress-controller-cr-client-ca
                bundle: ca.pem

eric-pc-up-timer-wheel:
  replicaCount: 5
  resources:
    timerWheel:
      limits:
        cpu: 2
      requests:
        cpu: 400m                      
